### ISSUE TITLE
Code General Listings UI

### ISSUE THREAD

**Issue by tariqule** [True-Stay/true-stay-app#13]
<img width="342" alt="Screen Shot 2020-11-19 at 11 42 14 AM" src="https://user-images.githubusercontent.com/45430120/99696071-46e98900-2a5c-11eb-9504-86287868d343.png">

**Listing details will be shown, the following info is included:
Listing Title/ Listing Pic/Listing Price/Listing Description/Listing Location/Listing Map/Listing Landlord/Listing Review**

**Comment by Rikinp5** [comment]
what bug are you talking about here @tariqule ?
